name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "0 * * * *" # https://crontab.guru

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "0xb4dc0d3x@gmail.com"
          git config --local user.name "0xb4dc0d3x"
          git add -A
          
          arr[0]="chore(bot): 0 auto commit"
          arr[1]="chore(bot): 1 auto commit"
          arr[2]="chore(bot): 2 auto commit"
          arr[3]="chore(bot): 3 auto commit"
          arr[4]="chore(bot): 4 auto commit"
          arr[5]="chore(bot): 5 auto commit"
          arr[6]="chore(bot): 6 auto commit"
          arr[7]="chore(bot): 7 auto commit"
          arr[8]="chore(bot): 8 auto commit"
          arr[9]="chore(bot): 9 auto commit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
